services:
    #
    # Validators
    #
    mapbender.validator.twig:
        class: Mapbender\CoreBundle\Validator\Constraints\TwigConstraintValidator
        arguments:
            - '@twig'
        tags:
            - { name: validator.constraint_validator }

    mapbender.validator.html:
        class: Mapbender\CoreBundle\Validator\Constraints\HtmlConstraintValidator
        arguments:
            - '@twig'
        tags:
            - { name: validator.constraint_validator }
